name: Docker Push Minimal Alpine

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库
      - uses: actions/checkout@v4

      # 2️⃣ 登录 GHCR
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3️⃣ Build 一个最小 Alpine 镜像
      - name: Build Docker image
        run: |
          echo -e "FROM alpine:latest\nCMD [\"echo\", \"Hello GHCR\"]" > Dockerfile
          docker build -t ghcr.io/jianboy/alpine-min:latest .

      # 4️⃣ Push 镜像
      - name: Push Docker image
        run: docker push ghcr.io/jianboy/alpine-min:latest
